// Generated by Wrangler by running `wrangler types`
// Extended with custom bindings

// AI Search binding type (not yet in @cloudflare/workers-types)
interface AiSearch {
	search(params: {
		query: string;
		rewrite_query?: boolean;
		max_num_results?: number;
		ranking_options?: { score_threshold?: number };
		reranking?: { enabled?: boolean; model?: string };
		filters?: Record<string, unknown>;
	}): Promise<{
		data: Array<{
			content: string;
			filename: string;
			score: number;
			metadata?: Record<string, unknown>;
		}>;
	}>;
	aiSearch(params: {
		query: string;
		max_num_results?: number;
	}): Promise<{
		response: string;
		data: Array<{
			content: string;
			filename: string;
			score: number;
		}>;
	}>;
}

interface Env {
	ENVIRONMENT: "production";
	STORAGE: R2Bucket;
	MNEMO_CONTENT: R2Bucket;
	DB: D1Database;
	RATE_LIMIT_KV: KVNamespace;
	AI: Ai;
	AI_SEARCH: AiSearch;
	VECTORIZE: VectorizeIndex;
	GEMINI_API_KEY: string;
	MNEMO_AUTH_TOKEN?: string;
	RESEND_API_KEY?: string;
	WRITE_PASSPHRASE?: string;
	ALERT_EMAIL?: string;
	DAILY_REQUEST_LIMIT?: string;
	DAILY_TOKEN_LIMIT?: string;
	// AI Search (v0.4)
	AI_SEARCH_NAME?: string;
	AI_SEARCH_CONFIDENCE_THRESHOLD?: string;
	AI_SEARCH_MAX_RESULTS?: string;
	// GitHub Webhooks
	GITHUB_WEBHOOK_SECRET?: string;
	GITHUB_TOKEN?: string;
}
